#!/bin/sh
#
# Pre-commit hook: auto-increment version in pubspec.yaml
# Versioning scheme: <major>.<minor>.<patch>+<build>
# Each commit bumps patch and build by 1.

PUBSPEC=pubspec.yaml

VERSION_LINE=$(grep '^version:' $PUBSPEC | tr -d '\r')
if [ -z "$VERSION_LINE" ]; then
    echo "Error: Could not find version in $PUBSPEC"
    exit 1
fi

VERSION=$(echo "$VERSION_LINE" | sed 's/version: //')
VERSION_NAME=$(echo "$VERSION" | cut -d'+' -f1)
BUILD_NUMBER=$(echo "$VERSION" | cut -d'+' -f2)

MAJOR=$(echo "$VERSION_NAME" | cut -d'.' -f1)
MINOR=$(echo "$VERSION_NAME" | cut -d'.' -f2)
PATCH=$(echo "$VERSION_NAME" | cut -d'.' -f3)

NEW_PATCH=$((PATCH + 1))
NEW_BUILD=$((BUILD_NUMBER + 1))
NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}+${NEW_BUILD}"

sed -i "s/^version: .*/version: ${NEW_VERSION}/" $PUBSPEC

git add $PUBSPEC

echo "Version bumped: ${VERSION} -> ${NEW_VERSION}"